# Generated by Django 4.1.4 on 2022-12-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('total_confirmed_cases', models.CharField(max_length=255)),
                ('total_deaths_cases', models.CharField(max_length=255)),
                ('total_recovered_cases', models.CharField(max_length=255)),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
